### ISSUE TITLE
Ignore or whitelist files

### ISSUE THREAD

**Issue by omar-at-hebbia** [pre-commit/pre-commit-hooks#1047]
Is there a way to ignore or whitelist a file? Thanks

**Comment by asottile** [comment]
have you read the docs?

**Comment by jahanson** [comment]
Since I happened upon this wonderful nugget, here's the answer I was looking for. 

For anyone else that finds this, just update `.pre-commit-config.yaml` and regex exclude the files.

https://pre-commit.com/#config-exclude 

> have you read the docs?

Also, possibly reference 'the docs' in the README. If you're going to ask people if they've read them.

https://github.com/pre-commit/pre-commit-hooks/blob/31903eabdb97f5a3375fb1ea419ff782de64d7e7/README.md

**Comment by asottile** [comment]
literally the first link in the readme and yet
