### ISSUE TITLE
Add filename pattern to *trigger* run on all files

### ISSUE THREAD

**Issue by OJFord** [pre-commit/pre-commit-hooks#128]
For sake of example, consider a hook that checks C function signature against header files in some way.

Such a hook would run only on files matching `\.c$` - but ideally would be _triggered_ by those matching `\.(c|h)$`.

It would be awesome if in the hooks.yaml and .pre-commit-config.yaml files a hook could be configured similarly to:
```yaml
files: \.c$
always_run: \.h$ 
```

I put it on `always_run` since I think that fits quite neatly - `test_all_when` or something might be a suitable alias:
- when `true`, the hook would run on all (not just staged) matching files, as it does currently;
- when a pattern, the hook would run on all (not just staged) matching files providing a staged file matches the `always_run` pattern

**Comment by asottile** [comment]
I think you could accomplish this from the tool's side instead of having to handle it in pre-commit.  Ideally I want to keep the interface as simple as possible, here's how I'd design what you're suggesting:

- Make a `.pre-commit-config.yaml` which has `files: '\.(c|h)$'
    - When the tool receives a .c file in the list of arguments it knows that only C has changed and can compare against the known header files (through whatever discovery method it wants to use (not limited to git))
    - When the tool receives a .h file in the list of arguments it knows that it needs to check all the C files for such a function.

Ideally I don't want to push that complexity into pre-commit as it seems very one-off (and I'd never use it) and can be accomplished through improved linters.

Worst case, if the linting tool itself cannot be modified, a simple proxy which does what I've described can be placed between the two.

Thoughts?

**Comment by asottile** [comment]
This issue is also not on the correct project, this is for the out-of-the-box hooks.  You probably want pre-commit/pre-commit (the framework itself).

**Comment by OJFord** [comment]
Whoops, sorry for posting on the wrong repo.

That would work, a bit messier (worse for the one I'm currently writing than the .c/.h example) but if you're not keen to support it then it's preferable to `always_run: true` which is my current solution, thanks.
