### ISSUE TITLE
check-added-large-files hook fails for old versions of `git`

### ISSUE THREAD

**Issue by bfrizb** [pre-commit/pre-commit-hooks#252]
The `check-added-large-files` hook fails for old version of `git` (which do not support `git lfs`).

Running `git lfs status --json` on an old version of git results No stdout (only stderr including "Error: unknown flag: --json"), and returns an exit code of zero (at least it does in cygwin). This causes the following code to break in `check_added_large_files.py`:

```
def lfs_files():
    try:
        # Introduced in git-lfs 2.2.0, first working in 2.2.1
        lfs_ret = cmd_output('git', 'lfs', 'status', '--json')
    except CalledProcessError:  # pragma: no cover (with git-lfs)
        lfs_ret = '{"files":{}}'

    return set(json.loads(lfs_ret)['files'])
```
^ Since no CalledProcessError is raised, `lfs_ret` is an empty still when `json.loads(lfs_ret)['files']` is called, resulting in: `ValueError: No JSON object could be decoded`.

**Comment by asottile** [comment]
The version of `git` is actually independent of the problem here, the actual problem is the version of `git-lfs`.

Unfortunately, it's not possible to make `git lfs` older than 2.2.1 work (and it's quite difficult to actually *detect* this case efficiently).

I think about the best we can do is document in the README the minimum version of `git-lfs` (and point them at the `git-lfs` documentation showing how to upgrade).

I did actually hit this while writing the feature branch for this but decided a hard failure vs falling back to an incorrect behaviour was the best choice here -- but the error message is indeed unfortunate.

**Comment by bfrisbie-tanium** [comment]
Thanks for the quick response @asottile, and yeah I can't think of a good work around for this :(

Feel free to close out this issue whenever you'd like.

**Comment by asottile** [comment]
I added a blurb to the readme about minimum git-lfs version
