### ISSUE TITLE
Option to force run check-merge-conflict

### ISSUE THREAD

**Issue by vinayinvicible** [pre-commit/pre-commit-hooks#300]
check-merge-conflict only runs when it detects merge/rebase in progress.
This means it will always pass on CI setups.

Am not sure if this should be fixed specifically for check-merge-conflict or make a generic CI functionality available via [pre-commit](https://github.com/pre-commit/pre-commit/)

**Comment by asottile** [comment]
This is a bit intentional, the hook is especially susceptible to false positives when run outside of a merge conflict due to matching things like [this](https://github.com/pre-commit/pre-commit-hooks/blame/9bf684c131befc87304489719223db5fb29f9ac7/README.md#L6)

That said, you could easily write a `local` `pygrep` hook which works almost the same, something like this:

```
-   repo: local
    hooks:
    -   id: naive-check-merge-conflict
        name: naive check-merge-conflict
        entry: '^(<<<<<<< |======= |>>>>>>> |=======$)'
        language: pygrep
```

for example against `pre-commit-hooks`:

```
$ pre-commit run naive-check-merge-conflict --all-files
naive check-merge-conflict...............................................Failed
hookid: naive-check-merge-conflict

CHANGELOG.md:39:=======
```

Might be able to get away with `exclude_types: [markdown]` to make it work better?

```
$ pre-commit run naive-check-merge-conflict --all-files
naive check-merge-conflict...............................................Passed
```

**Comment by vinayinvicible** [comment]
Setting up a local hook will run it on developer's machine too.

Our codebase is huge and we were not using pre-commits from the start. So, CI is setup to run using source and origin options instead of all files.

So, I am just looking for a way to trigger this hook on our CI setup.

**Comment by vinayinvicible** [comment]
I wasn't aware of manual stage being added.
Even to use this, I don't want to duplicate the merge conflict logic into `pygrep`. Is it possible to support `--force` as an optional argument for `check-merge-conflict`.

**Comment by asottile** [comment]
Sure, would need a PR but I'd accept that :)

Maybe `--assume-in-conflict`?
