### ISSUE TITLE
How to use flake8 plugins with pre-commit

### ISSUE THREAD

**Issue by ushuz** [pre-commit/pre-commit-hooks#311]
flake8 plugins are usually distributed through a standalone python package on PyPI, e.g. `flake8-print` `flake8-docstring`.

In theory, I can locate where pre-commit's venv is and install plugin packages into that venv by myself, but it's really hacky and hard to be deterministically done for all other teammates and CI. 

Does pre-commit provide some kind of mechanism to install extra packages into the venv it creates?

**Comment by asottile** [comment]
You're looking for [`additional_dependencies`](https://pre-commit.com/#pre-commit-configyaml---hooks).

**Comment by ushuz** [comment]
@asottile Thanks! Didn't noticed that option in docs.

**Comment by asottile** [comment]
No problem! thanks for the issue 🎉

**Comment by jnns** [comment]
Please excuse me commenting on a closed ticket but I have a question that is related to this issue and you hopefully can clear up easily.

Right now, our flake8 version-pins that we have in `requirements.txt` are duplicated in `.pre-commit-config.yaml` (see below). How do you make sure that they're not getting out of sync?

```
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.9'
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-bugbear==19.8.0',
            'flake8-coding==1.3.2',
            'flake8-comprehensions==3.0.1',
            'flake8-debugger==3.2.1',
            'flake8-deprecated==1.3',
            'flake8-docstrings==1.5.0',
            'flake8-isort==2.7.0',
            'flake8-pep3101==1.2.1',
            'flake8-polyfill==1.0.2',
            'flake8-print==3.1.4',
            'flake8-quotes==2.1.1',
            'flake8-string-format==0.2.3',
        ]
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.7
```

A perhaps more elegant solution could be to use a [repository local hook](https://pre-commit.com/#repository-local-hooks). That way, no `additional_dependencies` need to be specified.  The problem with this approach is that I'd need to hardcode the path to the projects virtualenv into `.pre-commit-config.yaml` and this path is not necessarily the same on my colleagues computers.

Is there an easy solution to this that i'm overlooking?

**Comment by asottile** [comment]
I've been deleting them from requirements.txt :man_shrugging:

**Comment by asottile** [comment]
@jnns you may be interested in https://github.com/pre-commit/pre-commit/issues/945

**Comment by jnns** [comment]
Thank you @asottile for the quick and helpful response! :tada: 

Deleting the dependencies from `requirements.txt` would mean for me to change the linter settings of my text editor to use the undeterministic path to pre-commit's virtualenv instead of the project's venv.

Luckily pre-commit allows to adapt the PATH environment variable in a repository local hook. So all our team's setups are accounted for:

```
repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: env -i PATH=./bin:./.venv/bin:./.virtualenv/bin python -m flake8
        language: system
        types: [python]

```

**Comment by asottile** [comment]
you don't need to use a non deterministic path if you use `pre-commit run flake8 --files ...` (which is designed for this purpose)

**Comment by okainov** [comment]
@asottile sorry for commenting on this old issue, but what would be the recommended approach to update the versions if one uses `additional_dependencies`? Because when I use `rev` I can run directly `pre-commit update` or so to get tags updated to the latest versions. However this does not update  `additional_dependencies` and it seems I need to keep track on them manually... Any recommendations how to automate this?
