### ISSUE TITLE
Pin down flake8 version

### ISSUE THREAD

**Issue by KPilnacek** [pre-commit/pre-commit-hooks#332]
Dear authors of pre-commit,

I've been using this for quite some time in CI and everything worked nicely. However, today, [new version of flake8](https://github.com/PyCQA/flake8/releases) came out and as I install `pre-commit` for every CI RUN new errors started to pop-out (W605 specifically).

Would it be possible to pin down the flake8 version in setup.py? And increase the version as versions of `pre-commit-hooks` increase?
I'm willing to make the PR.

With regards
Krystof

**Comment by asottile** [comment]
If you'd like to select a specific version, you can do that with:
```python
    additional_dependencies: [flake8==...]
```

**Comment by asottile** [comment]
But really, you should fix the new lint errors W605 is protecting you from a future `SyntaxError` ;)

I'm planning on adding some code to pyupgrade to automatically rewrite that (but haven't gotten around to it): https://github.com/asottile/pyupgrade/issues/47

**Comment by KPilnacek** [comment]
The problem are not the errors (we fixed them quickly) but that yesterday `pre-commit` passed and today not. (just for the record setting version of flake8 in it's `additional_dependencies` is unintuitive to me).

Good that there is a way to control the upgrades :-).

Thanks for the quick response.

**Comment by asottile** [comment]
You could, but that would kind of defeat the point of isolating the environments and letting pre-commit handle the hook installation.

That would look like this:

```yaml
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        types: [python]
        language: system
```

**Comment by asottile** [comment]
for now probably yes,  I'm hoping to add configuration directly to flake8 such that the roundabout through `pre-commit-hooks` isn't necessary (or make a mirrors repo) -- that way the exact version will already be pinned as `rev: ...`

**Comment by asottile** [comment]
`eslint` less so though, I think that's already pinned based on how the mirrors repo is set up.

personally I'd rather get hit by the linter changes and just fix them :)

**Comment by sloria** [comment]
OK, thanks.

> personally I'd rather get hit by the linter changes and just fix them :)

Yeah, that way is fine for most of my projects. For my work project, though, we have lots of devs working on the same codebase and tests take several minutes to run, so non-deterministic failures can be quite costly.

**Comment by asottile** [comment]
absolutely makes sense -- we did the same thing at yelp with their 5M monolith :sob:

**Comment by skorokithakis** [comment]
@KPilnacek is right here, we also thought that pinning to your repo would pin flake8 and were extremely surprised that our CI started failing all of a sudden. Please reconsider pinning to tool versions upstream (i.e. on your end).

**Comment by asottile** [comment]
it has always been this way and I don't have any intentions of breaking that here.  if you want repeatability there are options via `additional_options`.  as stated above, there's plans to move `flake8` out of this repository (as was already done with `autopep8`) and then there will be versioned releases tied to the flake8 version -- doing that here doesn't really work because we have our own version number

**Comment by asottile** [comment]
> I would like pinning for reproductivility but at the same time it would be great if "pre-commit auto-update" could find new versions. If I am not mistaken, this was the way it was supposed to work.

`pre-commit autoupdate` only knows about `rev` -- the strings in `additional_dependencies` are arbitrary and `pre-commit` makes no attempt to understand / modify them and simply passes them along to whatever installation tool is being used for the particular language.

**Comment by asottile** [comment]
that said, as stated above the plan is to (eventually) move the `flake8` hook out of `pre-commit-hooks` into a repository which updates with flake8 (maybe even flake8 itself now that I'm a maintainer).  this will use `rev` for the version and will function with `autoupdate`

**Comment by ssbarnea** [comment]
I am sure that you will find a nice solution in the end. Indeed flake8 itself would probably be the best but even having an integration repository with travis that only updates the hooks would be a good approach. 

While I am sure you can easily do it for flake8, there are extra benefits of doing it outside because lots of tool developers don't know abotu pre-commit and they are reluctant to modify their CI in order to do this, so if someone else is doing for them, it would be easier. 

And BTW, thanks for the good work, I am really glad you taken the flake8 maintenance.

**Comment by skorokithakis** [comment]
A simple solution would be to just pin Flake8 and everything else in this repo, so a given rev would always pull down the same versions.

I'm not sure who would expect to pin this repo to a given rev but have the tools themselves auto update. As such, this is surprising behavior to the majority of users, and I don't understand why it was elected to be this way.

**Comment by asottile** [comment]
I'm creating a pre-commit configuration in `flake8` so it can be used against a specific version.  If you'd like to +1 something [here's where to do that](https://gitlab.com/pycqa/flake8/merge_requests/268)

**Comment by ssbarnea** [comment]
@asottile Now there is a problem with this approach, does this mean that flake8 will be pinned to master instead of last release? Doing an autoupdate would move the ping to  the head of master... which is unlikely what user would want.

I think that the default behavior should be use user releases (tags) and only if users insists it could pin to specific revisions. The sha256 revision numbers are clearly not user friendly, as opposed to version numbers.

**Comment by asottile** [comment]
`autoupdate` already works exactly as you describe: tags by default and `--bleeding-edge` using shas (or tags if master is exactly a tag)

**Comment by asottile** [comment]
See [`pre-commit autoupdate`](https://pre-commit.com/#pre-commit-autoupdate)
