### ISSUE TITLE
auto add --- header to yaml files

### ISSUE THREAD

**Issue by ssbarnea** [pre-commit/pre-commit-hooks#348]
Following the already existing auto-fixing hooks that repair file endline or spaces at the end of line, we need one that that adds the `---` to any yaml files.

Having this hook would ease adoption of strict yamllint as most of the time people forget to add it.

**Comment by asottile** [comment]
if you ask me, I think the `---` header is silly and enforcing it's there is even sillier -- I haven't seen a good rational reason to use it.  even the [yamllint docs](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_start) don't have any rationale

that said, doing what you're asking for here should be pretty easy, I wouldn't be surprised if there's already a tool that does this (and/or better) -- could even probably do this with `sed` / `awk` probably

**Comment by ssbarnea** [comment]
@asottile I almost finished the new hook, I will make a PR to add it.

I found only one big benefit from using yamllint: is able to spot duplicate keys in dictionaries, a permanent source of bugs in Ansible playbooks.

If I remember well --- header is a must for any YAML document that can contain multiple objects as this is the separator.

**Comment by asottile** [comment]
if we switched from pyyaml to ruamel.yaml we'd get duplicate key checking by default :man_shrugging: 

and yeah it's necessary to separate multi-documents, in my experience multi-document files are the _exception_ and not the normal case

even then, it's unnecessary as a header, only as a separator:

```pycon
>>> list(yaml.load_all('foo\n---\nbar'))
['foo', 'bar']
```

**Comment by MarkusTeufelberger** [comment]
`>>> list(yaml.load_all('foo\n---\nbar'))`

^ Try to include a few `%` signs at line beginnings there (a valid character for yaml strings) and you'll see why this is not unnecessary. I don't think that this example is valid YAML by the way.

https://yaml.org/spec/1.2/spec.html <-- you are talking about "bare documents" (`9.1.3` in the spec), @ssbarnea about "explicit documents" (`9.1.4`). Both are good options to have, and if someone wants explicit documents it makes sense to offer the option. I wouldn't call it `fix-yaml` though since bare documents are specified too. `fix-explicit-yaml` maybe?

**Comment by ssbarnea** [comment]
I am closing it because I decided that I do not need it so much but if someone is doing a correct PR, I will support it.
