### ISSUE TITLE
debug statements - add wdb

### ISSUE THREAD

**Issue by dave1432** [pre-commit/pre-commit-hooks#451]
I think wdb should be added to this hook detection.
It is a nice web debugger based on a client-server application.
Link: https://github.com/Kozea/wdb

**Comment by asottile** [comment]
seems fine, would you like to submit a patch?

**Comment by dave1432** [comment]
sure, but I don't know how I should contribute here (first time contributing).

I forked the repo but I'm not sure how to run the tests.

Basically it's just adding 'wdb' to DEBUG_STATEMENTS and adding a test if it is necessary :)

**Comment by asottile** [comment]
sure!  you'd probably append to this: https://github.com/pre-commit/pre-commit-hooks/blob/45cb6a35b75736ac450096d0a93fe57daa9fc8dc/pre_commit_hooks/debug_statement_hook.py#L10

probably no need to add a test, since that code is already pretty well covered

if you want to run the tests locally, you can do so through [tox](https://tox.readthedocs.io/en/latest/) -- though they'll run in CI in the PR either way
