### ISSUE TITLE
List of hooks external to this repo?

### ISSUE THREAD

**Issue by ghostsquad** [pre-commit/pre-commit-hooks#462]
Is there a list of hooks by the community outside of this repo?

**Comment by ghostsquad** [comment]
Nevermind. I found it here:
https://pre-commit.com/hooks.html

Maybe this could be linked in the readme?

**Comment by asottile** [comment]
it's linked from https://pre-commit.com 👍

**Comment by ssbarnea** [comment]
@asottile No sure if you will find this useful but in order to cope with upcoming extra popularity from pre-commit, you may want to consider documenting users to expose their hooks using a github **topic**, like https://github.com/topics/pre-commit-hook

I taken this approach with cookiecutter, where the project was flooded by requests to list user-written templates, and where we documented the use of https://github.com/topics/cookiecutter-template in order to expose their templates.

This should save some maintenance costs and extra bonus is that by default the list is sorted by popularity (stars). The downside is that this depends on github. Still,  I do not see any reasons for anyone not to keep a github mirror, even if they use another platform for development.

**Comment by asottile** [comment]
I'm not planning to change how we're doing it until it's a problem -- that said, I've been using the github tag [pre-commit](https://github.com/topics/pre-commit)

also there are several repositories not hosted on github today which would be excluded by such a move

this comment is also off topic here :)
