### ISSUE TITLE
Don't break markdown by default

### ISSUE THREAD

**Issue by WhyNotHugo** [pre-commit/pre-commit-hooks#472]
By default, `trailing-whitespace` breaks markdown files by deleting line breaks.

There's [a setting](https://github.com/pre-commit/pre-commit-hooks#trailing-whitespace) to fix this, but I do think the default should be to include this flag -- otherwise running this tool out of the box removes line breaks in markdown.

Is there any reason for it _not_ to be the default? I can't image scenarios where trimming line breaks from markdown makes sense. Even if there were such scenarios, those users should configure that explicitly, not the other way around.

It's very off-putting for new users to have to configure the hook to _not_ break content.

**Comment by asottile** [comment]
I understand your frustration but please consider that the language you're using may construe a tone that's inappropriate for cordial discourse.  I maintain this software for free and in these trying times (I was laid off recently due to COVID) we could all use a little more empathy.

___

when we polled, most of our users did not make line breaks in markdown via trailing whitespace but instead semantic paragraphs so we changed the default to be less of a special case. there were more people that asked _why it didn't fix_ markdown files and were surprised to learn that trailing whitespace had significant meaning.  the option was left in for those in the minority which still use the weird markdown feature

the change is outlined in the 2.0.0 changelog: https://github.com/pre-commit/pre-commit-hooks/blob/master/CHANGELOG.md#200---2018-10-12

note also that the option was surprising from a `pre-commit` standpoint as well as it did not mesh well with the normal `files` / `exclude` / `types` behaviour (it ran on this file, why didn't it fix it!)

**Comment by WhyNotHugo** [comment]
Oh, I apologize if I sounded rude, it was definitely not my intention. I understand that this is volunteer work, and greatly appreciate the time and effort put into it. I've been using many of these hooks for both work and hobbies with great success!

Back to the topic of this issue, the current default is very dangerous, since it actually alters the semantic meaning of the files. Eg: imagine changing the indentation level in python, where blocks are defined by their indentation.

There are basically two defaults to be considered here:

- Keep markdown line breaks: May confuse users who don't understand the markup language they're using, but won't break anything. At a worst, their confusion will lead them to learn something new.
- Remove markdown line breaks: Will change how markdown files are parsed, and change the rendered results. It's also impossible to add non-paragraph line breaks (do the users of this poll not use line jumps in the docs?).

When we first spotted this we honestly considered a bug -- since we can across code that deleted meaningful content. (and I definitely think this is the key point here: **the default deletes meaningful user content**).
Is there no room for reconsidering this?

---

Also on topic: this particular hook is also the very [first example](https://github.com/pre-commit/pre-commit-hooks#using-pre-commit-hooks-with-pre-commit) at the top, but there's no warning that this hook is dangerous by default. It might be worth using another example, since it's a somewhat controversial example.

**Comment by asottile** [comment]
"dangerous" is the type of forceful language I'm concerned about ;) 

it's markdown it's not like it affects execution.

I've already addressed your queries above but I'll reiterate: the default will not be flip flopped again, most were very happy with the adjustment in 2.0.  if you want the behaviour you're asking for you can use the option (the option has not been removed despite it going against the general grain of the framework).  you're over-selling the """danger""" of a hook which changes whitespace in documentation files, it's not like it's putting a shellhole in your applications.
