### ISSUE TITLE
RFE: check scripts with shebangs are executable

### ISSUE THREAD

**Issue by scop** [pre-commit/pre-commit-hooks#543]
A check that does the opposite of `check-executables-have-shebangs` would be useful; one that verifies scripts with shebangs are executable. Maybe call it just `check-executability` or something.

Do you think that would be welcome here? If yes, I think I could have a go at writing one. Let me also know if you have a name you'd prefer for this.

**Comment by asottile** [comment]
it wasn't added with `check-executables-have-shebangs` because there are a lot of special cases and I don't really want to encode them into a script (since it'd be very noisy).  A number of things (mis)use first-line comments starting with `#!` to mean things that are different than shebangs unfortunately

it's still possible to write something like this, and it may still be useful for some, but that's why I've avoided incorporating it here so far

**Comment by scop** [comment]
Yeah, I'd keep the test simple and leave worrying about abuse of shebangs to those who do that, they can choose to use `exclude` the way they want, or just not use the check in the first place.

**Comment by asottile** [comment]
would you like to work on this?

**Comment by scop** [comment]
Sure, can do, just discussing desirability here first.
