### ISSUE TITLE
Feature: Add a param to check_json and check_yaml to support jsonschema

### ISSUE THREAD

**Issue by dnephin** [pre-commit/pre-commit-hooks#71]
Currently both `check_json` and `check_yaml` only parse the file, but there are lots of easy mistakes you can make (especially with yaml) where the file is "valid yaml", but not at all what you want or expected.

If these checks took an optional param `jsonschema` which should be a file path to a jsonschema, they could validate the file against the jsonschema, without the need to write a custom hook for each format.

**Comment by asottile** [comment]
Sounds like a good idea, want to take a first stab at it?

**Comment by ssbarnea** [comment]
While this is a very useful feature there is no standardized way to map yaml files to their schema. I hope that this will be sorted because for the moment I had to write specific linter for a schema.

I am closely watching https://github.com/redhat-developer/vscode-yaml and https://github.com/schemastore/schemastore/ in order to figure-out how we can achieve that.

Clearly the mapping between schemas and files needs to be very well curated because otherwise you end-up with false positives when running the tool.

**Comment by asottile** [comment]
since this hasn't really progressed I'm going to close this -- it might make sense to use some third party tool to do this (I've seen a few that have domain specific schema checking, and with pre-commit integration already)

**Comment by hugovk** [comment]
One option is to use https://github.com/Julian/jsonschema:

> It can also be used from console:
> 
> `$ jsonschema -i sample.json sample.schema`

Perhaps someone would like to create a new hook using that and send a PR to https://github.com/Julian/jsonschema?
