### ISSUE TITLE
The trailing-whitespaces hook should explain why it is not fixing .md files by default

### ISSUE THREAD

**Issue by Lucas-C** [pre-commit/pre-commit-hooks#74]
Hi,

Currently this hook display an error but does not auto-fix Markdown files.
Hence a user will repeatedly get the following output

```
Trim Trailing Whitespace................................................................Failed
hookid: trailing-whitespace

Fixing README.md
```

The `Fixing` bit of the message is especially misleading: the hook actually does NOT try to remove extra trailing whitespaces in Markdown files, unless you pass it a `--no-markdown-linebreak-ext` argument.

Would you agree to improve the message here ?

**Comment by asottile** [comment]
Yeah that feels a bug to me.  @dupuy what do you think?

**Comment by dupuy** [comment]
Message could indeed be improved (they almost always can be) - a fixed message indicating state of the flag should be quite easy, but it would be even better to indicate that trailing two-space line break was preserved only if there actually were any in the file in question.  I'd have to look at the code flow to see whether that would be practical to implement.  I have a long flight back to NYC tomorrow, might be able to look at it then, but otherwise am pretty occupied with a relocation back from Berlin and am not sure when in the next few weeks I might be able to do much about it apart from that in-flight window.

Sorry for the delayed response, I was on vacation last week and mostly off-line, saw the question via e-mail on my phone, but didn't have a practical way to respond intelligently.

**Comment by dupuy** [comment]
Reviewing this issue a bit further, I'm not sure about the possibly bigger problem, which is that the exit status indicates failure in the case that there is any trailing two-space line-break (even though it is not "fixed" unless an additional flag is given - and there is no way to leave it "unfixed" without reporting failure).  That really does feel like a bug to me - but my recollection of the code is pretty clear that the exit status is determined separately from the actual fixing code, and handling the trailing two-space line break specially only in files with markdown extensions would be a bit tricky there (which is why I didn't do that in the first place).  There might need to be a more significant refactoring (of at least the exit status handling in the trailing whitespace plugin) to solve that problem cleanly. Before I get into that, I'd like to know if there is a consensus that either

A. "fixing" plugins should (without any special options) fix anything that would cause a failure (so that after staging automatic changes, a second run would not fail - I'm not sure this is strictly true for existing plugins) meaning that failure should only be indicated when changes have been made (output messages might still be present, although much less likely to be read), or

B. if there should be another (mutually exclusive) option that not only preserves the trailing two-space line break but also suppresses the failure in that case (as there is a chance that the trailing whitespace is not intentional or even functional, depending on the markdown dialect and documentation style in use).

I would kind of lean towards B but am not totally convinced that forcing that additional user interaction (choose explicit 'allow' or 'fix' for trailing two-space line breaks) to prevent recurring failure is really necessary, as leaving the trailing two-space line break without a failure by default is probably going to pass unnoticed and without complaint (even with a non-failure warning about the fact they are not fixed) and has pretty much no functional downside. (I strongly suspect that this issue would never have been opened if the trailing two-space line break had not caused this plugin to report failure and abort the commits.)

**Comment by asottile** [comment]
(Excuse the brief reply, I'm also on vacation and on my phone).

Option A sounds most like the goal I'd like to have such that fixes require no intervention beyond staging.  I agree that falsely flagging a failure that doesn't exist or isn't fixed is a bug. We should fix it to avoid messages and nonzero exit codes when there are no failures and explain as best is possible why changes were made when necessary.

**Comment by Lucas-C** [comment]
Thanks for the detailed review.
I vote for Option A definitively.
I'm working on a pull request to implement that + including a bit of refactoring
Nothing is better than code to explain how code should behave :)

**Comment by sanmai-NL** [comment]
What's the status of this @Lucas-C? I'm also having issues with the hook not performing the fixes due to existence of Markdown files. When running `pre-commit run --all-files`, that's quite inconvenient.

**Comment by peterhil** [comment]
Anyone coming to this issue later on, and wondering what the `trailing-whitespace` actually fixed on Markdown files should look at the diff after running `pre-commit` or `git commit` with diff:

`git diff --ws-error-highlight=all`

There is a [really good SO answer](https://stackoverflow.com/a/5259137/470560) about using these git diff options and configuring them.

**Comment by sachin-suresh-rapyuta** [comment]
So, what is the final solution to this? I am using RST files, and I also feel that "Fixing..." is misleading. I am trying all ways to customize the output message, but was unsuccessful.

**Comment by asottile** [comment]
please report a new issue with details.  your problem is not the one listed here
