### ISSUE TITLE
Support for changed lines only

### ISSUE THREAD

**Issue by craig-davis** [pre-commit/pre-commit-hooks#93]
I've used [Overcommit](https://github.com/brigade/overcommit) in the past. Unfortunately, it is currently unable to run hooks that alter files. Pre-commit has been working great for this. However, there is one feature I miss - the ability to reference only the altered lines in a hook. 

For instance, you can compare the line number in an error message with the list of lines that are included in the diff, and then choose to ignore those unchanged lines. This can be very valuable in a legacy code base. 

Are there any provisions for such a thing in Pre-commit?

**Comment by struys** [comment]
Unfortunately pre-commit knows very little about the format of the error messages. pre-commit looks for "did this executable change code or did it return a non zero return code?" to determine if a hooked failed. The stdout/stderr of the hook isn't parsed by pre-commit making this feature request very difficult to implement.

At Yelp we think the existing approach works great for a legacy codebase. Eventually you want to run all the hooks on all the files in the codebase. Overtime all the issues are fixed in the codebase and they're fixed by a developer who is currently changing the file. That developer at least has a bit of context on whether or not a hook is making the correct change. The alternative to this is a single developer runs `pre-commit run --all-files` across the entire codebase and prays it doesn't somehow break something.

**Comment by craig-davis** [comment]
> prays it doesn't somehow break something

Roger that :smile: 

Thanks for the background on this. Probably best to keep this simple. I will admit that writing parsers for the output of some tools was non-trivial in Overcommit. I'm about to send a PR for additional php tooling to [hootsuite](https://github.com/hootsuite/pre-commit-php), and these are simple to write.

Thanks for all of the hard work on this!
